# Generated by Django 4.2.9 on 2024-01-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_about_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='key',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
